<?php
/**
 * Single meeting — video embed + transcript.
 *
 * The header is rendered here from scalar meta. The transcript, votes,
 * and agenda are loaded by assets/js/meeting.js from
 * /wp-json/wp/v2/meeting/{id} (segments_json is ~1MB, so it is fetched
 * after the page paints rather than inlined into the HTML).
 */
get_header();

while ( have_posts() ) :
    the_post();
    $id        = get_the_ID();
    $date      = get_post_meta( $id, 'meeting_date', true );
    $body      = get_post_meta( $id, 'meeting_body', true ) ?: 'Cambridge School Committee';
    $embed     = get_post_meta( $id, 'cablecast_embed_url', true );
    $agenda    = get_post_meta( $id, 'agenda_url', true );
    $summary   = get_post_meta( $id, 'summary', true );
    $origin    = get_post_meta( $id, 'summary_origin', true );
    $languages = array_filter( array_map( 'trim', explode( ',', (string) get_post_meta( $id, 'languages_available', true ) ) ) );
    ?>
    <div class="wrap">
        <?php cr_theme_plugin_notice(); ?>

        <header class="meeting-head">
            <p class="eyebrow"><?php echo esc_html( $body ); ?></p>
            <h1><?php the_title(); ?></h1>
            <div class="meta-line">
                <?php if ( $date ) : ?>
                    <time datetime="<?php echo esc_attr( $date ); ?>"><?php echo esc_html( cr_theme_format_date( $date ) ); ?></time>
                <?php endif; ?>
                <?php if ( $agenda ) : ?>
                    <a href="<?php echo esc_url( $agenda ); ?>" rel="noopener">Official agenda ↗</a>
                <?php endif; ?>
                <?php if ( count( $languages ) > 1 ) : ?>
                    <span>Captions in <?php echo count( $languages ); ?> languages on the video player</span>
                <?php endif; ?>
            </div>

            <?php if ( $summary && $origin !== 'pending' ) : ?>
                <div class="panel measure">
                    <h2>Summary
                        <?php if ( str_starts_with( (string) $origin, 'ai:' ) ) : ?>
                            <span class="tag tag--ai" title="Generated by <?php echo esc_attr( substr( $origin, 3 ) ); ?>. The transcript below is the source.">AI · <?php echo esc_html( substr( $origin, 3 ) ); ?></span>
                        <?php endif; ?>
                    </h2>
                    <p class="summary"><?php echo esc_html( $summary ); ?></p>
                </div>
            <?php endif; ?>
        </header>

        <div class="meeting-layout" id="meeting"
             data-id="<?php echo (int) $id; ?>"
             data-embed="<?php echo esc_url( $embed ); ?>">

            <aside class="meeting-aside">
                <div class="meeting-media">
                    <div class="player">
                        <?php if ( $embed ) : ?>
                            <iframe id="player" src="<?php echo esc_url( $embed ); ?>"
                                    title="Meeting video: <?php the_title_attribute(); ?>"
                                    allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
                        <?php endif; ?>
                    </div>
                    <div class="player-bar">
                        <span class="now" id="player-now">Click any line of the transcript to jump the video there.</span>
                        <button type="button" class="btn" id="follow-video" hidden>Follow video</button>
                        <button type="button" class="btn btn--ghost" id="copy-moment" hidden>Copy link to this moment</button>
                        <?php if ( $embed ) : ?>
                            <a class="small" id="watch-external" href="<?php echo esc_url( $embed ); ?>" target="_blank" rel="noopener">Watch on Cablecast ↗</a>
                        <?php endif; ?>
                    </div>
                </div>

                <section class="panel" id="agenda-panel" hidden aria-labelledby="agenda-heading">
                    <h2 id="agenda-heading">Agenda</h2>
                    <ul id="agenda-list"></ul>
                </section>

                <section class="panel" id="votes-panel" hidden aria-labelledby="votes-heading">
                    <h2 id="votes-heading">Possible votes <span class="tag" title="Flagged automatically from voting language in the captions. Check the video.">auto-flagged</span></h2>
                    <ul id="votes-list"></ul>
                </section>
            </aside>

            <section class="meeting-transcript" aria-labelledby="transcript-heading">
                <div class="transcript-tools">
                    <h2 id="transcript-heading">Transcript</h2>
                    <label for="find" class="screen-reader-text">Find in transcript</label>
                    <div class="field"><input type="search" id="find" placeholder="Find in this meeting" autocomplete="off"></div>
                    <span class="find-count" id="find-count" aria-live="polite"></span>
                    <button type="button" class="btn btn--ghost" id="find-prev" aria-label="Previous match" disabled>↑</button>
                    <button type="button" class="btn btn--ghost" id="find-next" aria-label="Next match" disabled>↓</button>
                </div>

                <div class="transcript" id="transcript">
                    <p class="status loading">Loading transcript</p>
                </div>
                <noscript><p class="status">The transcript needs JavaScript. The video above still plays.</p></noscript>
            </section>
        </div>
    </div>
    <?php
endwhile;

get_footer();
